[package]
name = "sudoku-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.3.0"
itertools = "0.10.5"
rand = "0.8.4"
rustyline = "12.0.0"

[features]
default = ["with-file-history"]
with-file-history = []
